import type { NextPage } from 'next'
import Head from 'next/head'
import { About } from '../components/About'
import Contact from '../components/Contact'
import { Main } from '../components/Main'
import Project from '../components/Project'
import Skill from '../components/Skill'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>MyPortfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main/>
      <About/>
      <Skill/>
      <Project/>
      <Contact/>
    </div>
  )
}

export default Home
